name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        server: ${{ secrets.SFTP_SERVER }}
        port: ${{ secrets.SFTP_PORT }}
        local_path: './source/*'
        remote_path: ${{ secrets.SFTP_PATH }}
        sftp_only: true
